# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hduser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
