# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_intro', models.TextField(verbose_name='博客页简介')),
            ],
            options={
                'verbose_name_plural': '博客页',
                'verbose_name': '博客页',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='评论者邮箱')),
                ('c_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='网页')),
                ('c_content', models.TextField(verbose_name='评论内容')),
                ('c_date', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='Pcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='博客分类')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '博客分类',
                'verbose_name': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100, verbose_name='博客标题')),
                ('p_content', models.TextField(verbose_name='博客内容')),
                ('p_views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('p_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('p_author', models.CharField(max_length=30, verbose_name='作者')),
                ('p_likes', models.IntegerField(default=0, verbose_name='点赞量')),
                ('p_iamge', models.ImageField(default=None, upload_to='static/img')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('p_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Pcategory', verbose_name='博客分类')),
            ],
            options={
                'verbose_name_plural': '博客',
                'verbose_name': '博客',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签',
                'verbose_name': '标签',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='p_tags',
            field=models.ManyToManyField(to='blogapp.Tags', verbose_name='标签'),
        ),
    ]
