# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20180625_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_name2',
            field=models.CharField(default=1, max_length=20, verbose_name='暂评论者'),
            preserve_default=False,
        ),
    ]
