# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment_c_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='c_name',
        ),
    ]
