# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_postuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(max_length=40, verbose_name='博客id')),
                ('u_id', models.IntegerField(max_length=40, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '点赞量',
                'verbose_name_plural': '点赞量',
            },
        ),
    ]
