# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_likes',
            field=models.IntegerField(default=100, verbose_name='点赞量'),
        ),
    ]
