# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigclassify',
            name='b_index',
            field=models.IntegerField(verbose_name='索引'),
        ),
        migrations.AlterField(
            model_name='buytoday',
            name='b_repertory',
            field=models.IntegerField(verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='c_repertory',
            field=models.IntegerField(verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='c_sales',
            field=models.IntegerField(verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='c_title',
            field=models.CharField(max_length=15, verbose_name='商品标题'),
        ),
        migrations.AlterField(
            model_name='smallclassify',
            name='s_index',
            field=models.IntegerField(verbose_name='索引'),
        ),
    ]
