# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0002_auto_20190618_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
