# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0003_auto_20190619_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytoday',
            name='b_sales',
            field=models.CharField(default=1, max_length=20, verbose_name='销量'),
            preserve_default=False,
        ),
    ]
