# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0004_buytoday_b_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buytoday',
            old_name='b_activityPrice',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='buytoday',
            old_name='b_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='buytoday',
            old_name='b_originalPrice',
            new_name='original_price',
        ),
        migrations.RenameField(
            model_name='buytoday',
            old_name='b_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='c_current_price',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='c_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='c_original_price',
            new_name='original_price',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='c_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='buytoday',
            name='b_sales',
            field=models.CharField(default=0, max_length=20, verbose_name='销量'),
        ),
    ]
