# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0005_auto_20190623_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('commodity_nums', models.IntegerField(default=1, verbose_name='商品数量')),
                ('cart_commoditys_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodityapp.ShopCart', verbose_name='购物车商品id')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'shopCart',
            },
        ),
    ]
