# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0008_auto_20190625_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='cart_commoditys_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commodityapp.ShopCart', verbose_name='购物车商品id'),
        ),
    ]
