# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0009_auto_20190625_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='cart_commoditys_id',
            field=models.IntegerField(verbose_name='购物车商品id'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodityapp.User'),
        ),
    ]
