# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0010_auto_20190625_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='user',
            field=models.ManyToManyField(to='commodityapp.User'),
        ),
    ]
