# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0011_commodity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='user',
            field=models.ManyToManyField(null=True, to='commodityapp.User'),
        ),
    ]
