# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0014_commodity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='user',
        ),
    ]
