# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0016_commodity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytoday',
            name='deatailPic',
            field=models.ImageField(default=1, upload_to='buytoday/', verbose_name='详情图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='deatailPic',
            field=models.ImageField(default=1, upload_to='buytoday/', verbose_name='详情图片'),
            preserve_default=False,
        ),
    ]
