# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodityapp', '0017_auto_20190627_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='属性详情')),
            ],
            options={
                'verbose_name': '属性详情',
                'verbose_name_plural': '属性详情',
                'db_table': 'AttributeDetail',
            },
        ),
        migrations.AddField(
            model_name='buytoday',
            name='attribute',
            field=models.CharField(default=None, max_length=5, null=True, verbose_name='属性'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='attribute',
            field=models.CharField(default=None, max_length=5, null=True, verbose_name='属性'),
        ),
        migrations.AlterField(
            model_name='buytoday',
            name='deatailPic',
            field=models.ImageField(null=True, upload_to='buytoday/', verbose_name='详情图片'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='deatailPic',
            field=models.ImageField(null=True, upload_to='buytoday/', verbose_name='详情图片'),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='buyToday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodityapp.BuyToday'),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='commoDity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodityapp.Commodity'),
        ),
    ]
